# Generated by Django 4.2.11 on 2024-04-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('CD', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='StreetSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nodes')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('nodes_list', models.CharField(max_length=1000)),
                ('opt_route', models.CharField(max_length=1000)),
                ('distance', models.FloatField()),
                ('distributor center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nodes')),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
